# Site settings
title: Kenny Weigel
email: kennyweigel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer currently building pieces of the internet from Portsmouth, NH.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kennyweigel.com" # the base hostname & protocol for your site
# twitter_username: kennyweigel
github_username:  kennyweigel
host: 0.0.0.0
# Build settings
markdown: kramdown
